slam_toolbox:
  ros__parameters:
    use_sim_time: true

    # Frames (MATCH YOUR ROBOT)
    map_frame: map
    odom_frame: odom
    base_frame: base_footprint

    # Laser
    scan_topic: /gazebo_ros_laser/out

    # QoS (CRITICAL for Gazebo)
    qos_overrides:
      /gazebo_ros_laser/out:
        reliability: best_effort
        durability: volatile

    # SLAM behavior
    mode: mapping
    publish_tf: true
    publish_map: true
    transform_publish_period: 0.05

    # Performance (safe defaults)
    resolution: 0.05
    max_laser_range: 12.0
